name = "Compose"
license = "MIT"
licenselink = "https://github.com/onweru/compose/blob/master/LICENSE"
description = "A hugo theme for documentation sites. It's inspired by forestry.io's docs page"
homepage = "https://github.com/onweru/compose"
demosite = "https://composedocs.netlify.app/"
tags = ["dark mode", "docs", "dark", "blog", "search", "documentation"]
features = ["dark mode", "docs", "dark", "blog", "search", "documentation"]
min_version = "0.123.0"

[author]
name = "Weru"
homepage = "https://github.com/onweru"
