[[main]]
name = "Blog"
weight = 4
url = "blog/"

[[main]]
name = "Docs"
weight = 2
url = "docs/"

[[main]]
name = "Tutorials"
weight = 2
url = "tutorials/"

[[main]]
name = "Example"
weight = 3
url = "https://composedocs.netlify.app"
